basic: |-
  +----------------------------+
  {{title}}
  ------------------------------
  {{content}}
  ------------------------------
  {{footer}}
  +----------------------------+

help: |-
  {{name}}æ˜¯ä¸€æ¬¾ AI Native çš„æ™ºèƒ½åŠ©æ‰‹ï¼Œå¯ç”¨äºä¸ªäººã€ç¾¤ç»„æ™ºèƒ½ç®¡ç†ã€ååŒã€‚
  ------------------------------
  ç›®å‰æ”¯æŒä»¥ä¸‹å­åŠŸèƒ½ï¼š
  - A1: è¯é¢˜çº§åˆ«çš„ AI èŠå¤©
    /enable-uni-chatter: å¯ç”¨AIèŠå¤©
    /disable-uni-chatter: ç»“æŸAIèŠå¤©
    /list-topics: æŸ¥è¯¢å†å²è¯é¢˜
    /set-topic [N]: ç»§ç»­ç¬¬Nä¸ªè¯é¢˜
    /new-topic [TITLE]: å¼€å¯æ–°è¯é¢˜
  
  - A2: ä¿¡æ¯æ€»ç»“ï¼ˆå·²æ”¯æŒï¼šè®¢é˜…å·æ–‡ç« â€¦â€¦ï¼‰
    /enable-uni-parser: å¯ç”¨ä¸‡èƒ½è§£æå™¨
    /disable-uni-parser: åœç”¨ä¸‡èƒ½è§£æå™¨
  
  - A3: ä»»åŠ¡ç®¡ç†
    /todo: æŸ¥è¯¢ä¸ªäººä»»åŠ¡åˆ—è¡¨
    /add-todo [TITLE]: æ–°å¢ä¸ªäººä»»åŠ¡
    /set-todo [N] [STATUS]: ğŸ“Œä»»åŠ¡çŠ¶æ€
  ------------------------------
  å‘½ä»¤åˆ—è¡¨ï¼š
  /: å¸®åŠ©
  /ding: å¿ƒè·³æ£€æµ‹
  /status: æŸ¥è¯¢çŠ¶æ€
  /list-models: æŸ¥è¯¢æ¨¡å‹åˆ—è¡¨
  /set-model: è®¾ç½®æ¨¡å‹
  /help [FEAT]: æŸ¥è¯¢å­åŠŸèƒ½å¸®åŠ©

status: |-
  Basic:
    alive-time: {{aliveTime}}
  ------------------------------
  Preference:
    model: {{preference.model}}
    backend: {{preference.backend}}
  ------------------------------
  Conv:
    uni-chatter-enabled: {{{conv.uniChatterEnabled}}}
    uni-parser-enabled: {{{conv.uniParserEnabled}}}
